version: '3.8'

services:
    fend:
      build: ./example-frontend
      ports:
        - 5000:5000
    bend:
      build: ./example-backend
      environment:
        - REDIS_HOST=redis
        - POSTGRES_HOST=db
        - POSTGRES_USER=juho
        - POSTGRES_PASSWORD=learningdocker
      ports:
       - 8080:8080
    redis:
      image: redis
      ports:
       - 6379:6379
      command: redis-server --save 20 1
      volumes: 
       - ./cache:/data
    db:
      image: postgres:13.6-alpine
      restart: unless-stopped
      environment:
        - POSTGRES_USER=juho
        - POSTGRES_PASSWORD=learningdocker
      volumes:
        - ./database:/var/lib/postgresql/data
    proxy:
      image: nginx
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
      ports:
        - 80:80
      depends_on:
        - fend
        - bend

volumes:
  database:
  cache: